---
name: buildstack

releases:
- name: buildstack
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: buildstack
  azs:
  - z1
  instances: 1
  jobs:
  - name: app
    release: buildstack
    properties: {}
  vm_type: g1-small
  stemcell: default
  networks:
  - name: default
