platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
inputs:
- name: bbl-state
run:
  path: /bin/bash
  args:
  - -c
  - | 
    pushd bbl-state/bbl-state
      source <(bbl print-env)
      JUMPBOX_USER="jumpbox"; export JUMPBOX_USER
      JUMPBOX_HOST=$(bosh int <(bbl outputs) --path /jumpbox_url | cut -d: -f1); export JUMPBOX_HOST
      # set up jumpbox ssh tunnel
      instance_info=$(bosh --json instances -i); export instance_info
      ip=$(jq -r .Tables[0].Rows[0].ips <<< "$instance_info")
      # shellcheck disable=SC2029
      ssh -o StrictHostKeyChecking=no -fNnL "8080:$ip:8080" -i "$JUMPBOX_PRIVATE_KEY" "$JUMPBOX_USER@$JUMPBOX_HOST"
      trap "pkill ssh" EXIT
      sleep 10
      set -o pipefail
      curl --fail --retry-max-time 300 --retry-delay 1 --retry 300 http://localhost:8080/login 2>&1 | grep -v "Unlock Jenkins"
    popd
