instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: nexus
    properties:
      nexus:
        admin:
          password: admin123
        deployer:
          password: admin123
    release: devtools
  name: nexus
  networks:
  - name: default
  stemcell: default
  vm_extensions:
  - internet-required
  - nexus-pool
  vm_type: default


name: buildstack
os: ubuntu-trusty

releases:
- name: devtools
  version: latest
  
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3541.12"

update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000

variables:
- name: nexus_admin_password
  type: password
- name: nexus_deployer_password
  type: password

