name: ((deployment_name))
instance_groups:
- name: gerrit
  azs: [z1]
  instances: 1
  jobs:
  - name: gerrit
    release: devtools
    properties:
      gerrit:
        database:
          password: ((gerrit_database_password))
  networks:
  - name: default
  persistent_disk_pool: 100GB
  stemcell: default
  vm_type: small

releases:
- name: devtools
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000

variables:
- name: gerrit_database_password
  type: password

