---
resource_types:
- name: google-cloud-storage
  type: docker-image
  source:
    repository: frodenas/gcs-resource
- name: bbl-state-resource
  type: docker-image
  source:
    repository: cfinfrastructure/bbl-state-resource

resources:
- name: bbl-state
  type: git
  source:
    branch: master
    uri: ((bbl-state-url))
    username: ((git-credentials.username))
    password: ((git-credentials.password))
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
- name: devtools-boshrelease
  type: git
  source:
    uri: git@github.com:finkit/devtools-boshrelease
    branch: master
    private_key: ((github-finkit-ssh-key))
    ignore_paths: ci/**
- name: release-tarballs
  type: google-cloud-storage
  source:
    bucket: ((dev-build-automate-release-tarballs.bucket))
    json_key: ((concourse_project_google_key))
    versioned_file: devtools-boshrelease/dev-release.tgz

jobs:
- name: create-dev-release
  plan:
  - aggregate:
    - get: devtools-boshrelease
      trigger: true
  - task: create-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: engineerbetter/pcf-ops
      inputs:
      - name: devtools-boshrelease
      outputs:
      - name: release-tarballs
      run:
        path: bash
        args:
        - -c
        - |
          mkdir -p release-tarballs/devtools-boshrelease
          bosh create-release \
            --tarball=release-tarballs/devtools-boshrelease/dev-release.tgz \
            --dir=devtools-boshrelease \
            --timestamp-version
  - put: release-tarballs
    params: { file: release-tarballs/devtools-boshrelease/dev-release.tgz }
- name: test-jenkins
  serial: true
  plan:
  - aggregate:
    - get: release-tarballs
      passed: [create-dev-release]
    - get: cf-deployment-concourse-tasks
    - get: bbl-state
  - task: deploy-bosh
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    input_mapping:
      bbl-config: bbl-state
      bbl-state: bbl-state
    output_mapping:
      updated-bbl-state: updated-bbl-state
    params:
      BBL_ENV_NAME: test-jenkins # TODO: Rename me after bbl-down works
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcp.key))
      BBL_GCP_REGION: ((gcp.region))
      BBL_IAAS: gcp
      BBL_STATE_DIR: bbl-state/test-jenkins
      SKIP_LB_CREATION: true
    ensure:
      put: bbl-state
      params:
        repository: updated-bbl-state
        rebase: true
